-- Seed data for data_sources table
-- Known organizations and sources that provide victim data

INSERT INTO data_sources (slug, name, full_name, name_en, name_fa, name_de, url, description_en, credibility, source_type, country_code, is_active, created_at, updated_at) VALUES
(
  'hrana',
  'HRANA',
  'Human Rights Activists News Agency',
  'Human Rights Activists News Agency',
  'خبرگزاری هرانا',
  'Human Rights Activists News Agency',
  'https://www.hra-news.org',
  'Independent news agency focused on human rights violations in Iran. One of the most comprehensive sources for documented cases of state violence.',
  'HIGH',
  'NGO',
  'US',
  true,
  NOW(),
  NOW()
),
(
  'boroumand',
  'Boroumand Center',
  'Abdorrahman Boroumand Center for Human Rights in Iran',
  'Abdorrahman Boroumand Center',
  'بنیاد عبدالرحمن برومند',
  'Abdorrahman Boroumand Zentrum',
  'https://www.iranrights.org',
  'Non-profit organization dedicated to the promotion of human rights and democracy in Iran. Maintains comprehensive database of victims.',
  'HIGH',
  'NGO',
  'US',
  true,
  NOW(),
  NOW()
),
(
  'amnesty',
  'Amnesty International',
  'Amnesty International',
  'Amnesty International',
  'عفو بین‌الملل',
  'Amnesty International',
  'https://www.amnesty.org',
  'Global human rights organization. Provides verified reports on human rights violations in Iran.',
  'HIGH',
  'NGO',
  'GB',
  true,
  NOW(),
  NOW()
),
(
  'ihr',
  'IHR',
  'Iran Human Rights',
  'Iran Human Rights',
  'ایران حقوق بشر',
  'Iran Human Rights',
  'https://iranhr.net',
  'Norwegian-based human rights organization documenting executions and killings in Iran.',
  'HIGH',
  'NGO',
  'NO',
  true,
  NOW(),
  NOW()
),
(
  'wikipedia-wlf',
  'Wikipedia (WLF)',
  'Wikipedia - List of deaths in the Mahsa Amini protests',
  'Wikipedia',
  'ویکی‌پدیا',
  'Wikipedia',
  'https://en.wikipedia.org/wiki/List_of_deaths_in_the_Mahsa_Amini_protests',
  'Community-maintained Wikipedia article documenting victims of the Woman Life Freedom protests.',
  'MEDIUM',
  'COMMUNITY',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'iranvictims',
  'iranvictims.com',
  'iranvictims.com',
  'iranvictims.com',
  'قربانیان ایران',
  'iranvictims.com',
  'https://iranvictims.com',
  'Database of victims of the Islamic Republic of Iran.',
  'MEDIUM',
  'MEMORIAL_PROJECT',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'iranrevolution',
  'iranrevolution.org',
  'Iran Revolution Documentation',
  'Iran Revolution Documentation',
  'مستندسازی انقلاب ایران',
  'Iran Revolution Dokumentation',
  'https://iranrevolution.org',
  'Memorial project documenting victims with Farsi biographical information.',
  'MEDIUM',
  'MEMORIAL_PROJECT',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'telegram-rtn',
  'Telegram RTN',
  'Telegram @RememberTheirNames',
  'Remember Their Names (Telegram)',
  'اسامی‌شان را به یاد بیاوریم',
  'Remember Their Names (Telegram)',
  'https://t.me/RememberTheirNames',
  'Telegram channel documenting victims of state violence with photos and biographical information.',
  'MEDIUM',
  'SOCIAL_MEDIA',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'community',
  'Community Submissions',
  'Community-submitted information',
  'Community Submissions',
  'اطلاعات ارسالی جامعه',
  'Community-Beiträge',
  NULL,
  'Information submitted by family members, friends, and witnesses through the memorial submission form.',
  'UNVERIFIED',
  'COMMUNITY',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'iranmonitor',
  'Iran Monitor',
  'Iran Monitor Memorial',
  'Iran Monitor Memorial',
  'ایران مانیتور',
  'Iran Monitor Memorial',
  'https://www.iranmonitor.org/memorial',
  'Structured API version of the @RememberTheirNames Telegram channel. Provides JSON access to memorial data with photos and biographical information.',
  'MEDIUM',
  'MEMORIAL_PROJECT',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'telegram-vahid',
  'Vahid Online',
  'Telegram @VahidOnline',
  'Vahid Online (Telegram)',
  'وحید آنلاین',
  'Vahid Online (Telegram)',
  'https://t.me/VahidOnline',
  'Citizen journalism Telegram channel (934K subscribers) documenting protest victims with photos and names. Covers recent casualties from ongoing demonstrations.',
  'MEDIUM',
  'SOCIAL_MEDIA',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'un-ffm',
  'UN FFM',
  'United Nations Fact-Finding Mission on Iran',
  'UN Fact-Finding Mission',
  'هیئت حقیق‌یاب سازمان ملل',
  'UN-Untersuchungskommission',
  'https://www.ohchr.org/en/hr-bodies/hrc/iran-ffm',
  'UN-mandated independent fact-finding mission documenting human rights violations in Iran.',
  'HIGH',
  'GOVERNMENT',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'grokipedia',
  'Grokipedia',
  'Grokipedia (xAI)',
  'Grokipedia',
  'گروکی‌پدیا',
  'Grokipedia',
  'https://grokipedia.com',
  'AI-generated wiki by xAI (launched 2025). Used as match-only enrichment: provides biographical context paragraphs and external cross-references; never the sole source for dates or facts. Tier: community. Pipeline: tools/enricher/pipeline/grokipedia.py.',
  'LOW',
  'COMMUNITY',
  'US',
  true,
  NOW(),
  NOW()
);
